Sprint 13
Vagner-Viktor/java-filmorate pull request #14
Opened 2024-06-11 15:13 UTC by Vagner-Viktor

Доработаны задачи:
1. Удаление фильмов и пользователей. 2 SP (add-remove-endpoint)
2. Добавление режиссёров в фильмы. 4 SP (add-director)
3. Функциональность «Отзывы». 4 SP (add-reviews)
4. Вывод самых популярных фильмов по жанру и годам. 2 SP (add-most-populars)
5. Функциональность «Поиск». 3SP (add-search)
6. Функциональность «Лента событий». 3 SP (add-feed)

2024-06-14 05:12 UTC, ErkinKasymaliev requested changes
привет!
Ребята, хорошая работа!
Видна командная работа, все выдержанно в одном стиле -- и это радует!
Но есть замечания:
1) в запросах вы join-ите таблицы, которые потом не используете в Селесте
2) в хранилище не надо инжектить другие хранилища
3) методы должны быть семантические верными, например, если метод имеет тип boolean, то в название должно быть isSomething, если он что то проверяет, то void, например void checkSomething и внутри бросать исключение или что то легировать если проверка не прошла

2024-06-14 05:12 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +    private final UsabilityStateStorage usabilityStateStorage;
а вот это не хорошо, не надо в хранилище инжектить другое, каждое хранилище отвечает за работу со своим доменом. Комбинировать методы нескольких в хранилищах вы можете в сервисах, в данном случае в ReviewService

2024-06-14 21:07 UTC, Vagner-Viktor commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +    private final UsabilityStateStorage usabilityStateStorage;
исправили

2024-06-14 21:08 UTC, Vagner-Viktor commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                    LEFT JOIN "films_genre" AS fg ON fg."film_id" = f."film_id"
исправили

2024-06-14 21:08 UTC, Vagner-Viktor commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                    LEFT JOIN "films_genre" AS fg ON fg."film_id" = f."film_id"
исправили

2024-06-14 21:10 UTC, Vagner-Viktor commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
>              LEFT JOIN "likes" AS l ON l."film_id" = f."film_id"
исправили.
обогащаем фильмы через фкнкции setFilmsGenres, setFilmsDirectors, setFilmsLikes

2024-06-14 21:10 UTC, Vagner-Viktor commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private static final String FILMS_GET_POPULAR_QUERY_WITH_GENRE = """
исправили

2024-06-14 21:10 UTC, Vagner-Viktor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDbStorage.java
> +    public boolean checkDirectorExists(long id) {
исправили

2024-06-14 21:13 UTC, Vagner-Viktor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDbStorage.java
> +            throw new NotFoundException("Id режисера должен быть указан");
исправили

2024-06-15 10:59 UTC, ErkinKasymaliev approved these changes
привет!
работа принята!

2024-06-15 12:16 UTC, merged