Add database
Vagner-Viktor/java-filmorate pull request #7
Opened 2024-05-26 16:52 UTC by Vagner-Viktor

Техническое задание 12

2024-05-27 06:03 UTC, ErkinKasymaliev requested changes
привет! хорошая работа, оставил комменты

2024-05-27 06:03 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            FROM "films" AS f
genre надо тоже подтянуть.
И еще, вы проверили объект правильно маппиться?

2024-05-27 06:03 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            LEFT JOIN "mpas" AS r ON  f."mpa_id" = r."mpa_id"
genre тоже нужно

2024-05-27 08:10 UTC, Vagner-Viktor commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            FROM "films" AS f
т.к. жанров и лайков может быть больше одного, - я подтягиваю их отдельно в

```
public class FilmRowMapper implements RowMapper<Film> {
    private final GenreStorage genreStorage;
    private final LikeStorage likeStorage;
```

2024-05-27 19:25 UTC, Vagner-Viktor commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            LEFT JOIN "mpas" AS r ON  f."mpa_id" = r."mpa_id"
аналогично предыдущему комментарию

2024-05-28 05:05 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/FilmRowMapper.java
> +        film.setGenres(genreStorage.findGenresOfFilm(film.getId()));
опачки, а вот это я не увидел!
так делать нельзя, потому что:
1) в mapper только маппинг, никаких запросов в бд быть не должно
2) представим что у вас 1000 фильмов подтянулось и genreStorage.findGenresOfFilm с likeStorage.findLikesOfFilm вызовится 1000 раз каждый -- а это плохо, очень плохо!

поэтому вы в одно запросе должны заджойнить кроме mpa, также genre и лайки и здесь брать их из result set и маппить.

поправьте везде где такое встречается

2024-05-28 21:25 UTC, Vagner-Viktor commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/FilmRowMapper.java
> +        film.setGenres(genreStorage.findGenresOfFilm(film.getId()));
Правильно я понимаю, что предполагалось, что все жанры должны попасть в одну ячейку, котору потом парсить нужно? Аналогично по лайкам?
Иначе, на 3 жанра мы получим 3 строки с данными и через RowMapper мы не получим нужный объект.


Я сдеал немного по другому: вынес получение списка всех жанров и лайков по запрашиваемым фильмам в отдельные запросы.
 
Итого, на получение списка всех фильмов + лайки + жанры - 3 запроса.

2024-05-31 05:30 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-05-31 05:30 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private void setFilmsGenres(Collection<Film> films) {
в принципе неплохое решение

2024-05-31 06:01 UTC, Vagner-Viktor commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private void setFilmsGenres(Collection<Film> films) {
отлично, спасибо

2024-05-31 06:01 UTC, merged